#!/bin/sh
[ -n "$IPKG_INSTROOT" ] && exit 0

# 重载 rpcd（不打断当前会话），配置文件已经通过 conffiles 机制安装/保留
[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload >/dev/null 2>&1

/etc/init.d/miaomiaowu enable
/etc/init.d/miaomiaowu start
exit 0
